# Permalinks
permalink:        pretty 
relative_permalinks: true

# Setup
title:            Rico <span>&amp;</span> Feliz 
tagline:          Finanzas simples 
url:              http://ricoyfeliz.net
paginate:         5
baseurl:          /
author:
  name:           Juan Olvera 
  url:            https://twitter.com/ricoyfelizblog
  email:          juan@ricoyfeliz.net

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/thinkxl/ricoyfeliz

# Plugins 
gems:
  - jekyll-redirect-from
