# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rico & Feliz 
tagline:          Finanzas simples 
url:              http://getpoole.com
paginate:         3
baseurl:          /
author:
  name:           Juan Olvera 
  url:            https://twitter.com/ricoyfelizblog
  email:          juan@ricoyfeliz.net

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/thinkxl/ricoyfeliz
